name: Build and Deploy

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Build
        run: |
          echo "Building the project..."
          # Add your actual build commands here
          sleep 5s

      - name: Trigger Automation Tests
        shell: bash
        run: |
          echo "Triggering automation workflow..."
          
          status_code=$(curl -o /dev/null -s -w "%{http_code}\n" -X POST -H "Accept: application/vnd.github.everest-preview+json" \
           -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
           --data '{"event_type": "trigger-automation"}' \
           https://api.github.com/repos/Indra512/PlaywrightCucumberJavaScript/dispatches)

           echo "GitHub API Response Status Code: $status_code"
           
           if [ "$status_code" -ne 204 ]; then
            echo "Failed to trigger automation workflow! Received status code: $status_code"
            exit 1
          fi

          echo "Automation workflow triggered successfully."

      - name: Get Latest Workflow Run ID
        id: get-workflow-id
        run: |
          run_id=$(curl -s -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
                  "https://api.github.com/repos/Indra512/PlaywrightCucumberJavaScript/actions/runs" | \
                  jq -r '.workflow_runs[0].id')
          echo "Latest Workflow Run ID: $run_id"
          echo "workflow_id=$run_id" >> $GITHUB_ENV

      - name: Wait for Automation Workflow to Complete
        run: |
          echo "Checking automation workflow status..."
          while true; do
            status=$(curl -s -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
                    "https://api.github.com/repos/Indra512/PlaywrightCucumberJavaScript/actions/runs/${{ env.workflow_id }}" | \
                    jq -r '.status')

            echo "Current automation workflow status: $status"

            if [[ "$status" == "completed" ]]; then
              conclusion=$(curl -s -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
                          "https://api.github.com/repos/Indra512/PlaywrightCucumberJavaScript/actions/runs/${{ env.workflow_id }}" | \
                          jq -r '.conclusion')

              if [[ "$conclusion" == "success" ]]; then
                echo "Automation workflow completed successfully."
                exit 0
              else
                echo "Automation workflow failed."
                exit 1
              fi
            fi

            echo "Waiting for 30 seconds before checking again..."
            sleep 30
          done
