name: Build and Deploy

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: 
      - automation-success
      - automation-failure

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Build
        run: |
          echo "Building the project..."
          # Add your actual build commands here
          sleep 5s

      - name: Trigger Automation Tests
        run: |
          echo "Triggering automation workflow..."
          
          status_code=$(curl -o /dev/null -s -w "%{http_code}\n" -X POST -H "Accept: application/vnd.github.everest-preview+json" \
           -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
           --data '{"event_type": "trigger-automation"}' \
           https://api.github.com/repos/Indra512/PlaywrightCucumberJavaScript/dispatches)

           echo "GitHub API Response Status Code: $status_code"
           
           if [ "$status_code" -ne 204 ]; then
            echo "Failed to trigger automation workflow! Received status code: $status_code"
            exit 1
          fi
          echo "Automation workflow triggered successfully."
          
  wait-for-automation:
    runs-on: ubuntu-latest
    if: github.event_name == 'repository_dispatch'  # Runs only when triggered by repository_dispatch

    steps:
      - name: Check Automation Result
        run: |
          if [[ "${{ github.event.action }}" == "automation-success" ]]; then
            echo "Automation tests passed!"
            exit 0
          else
            echo "Automation tests failed!"
            exit 1
          fi
