name: Build and Deploy

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Build
        run: |
          echo "Building the project..."
          # Add your actual build commands here
          sleep 5s

      - name: Trigger Automation Tests
        shell: bash
        run: |
          echo "Triggering automation workflow..."
          
          status_code=$(curl -o /dev/null -s -w "%{http_code}\n" -X POST -H "Accept: application/vnd.github.everest-preview+json" \
           -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
           --data '{"event_type": "trigger-automation"}' \
           https://api.github.com/repos/Indra512/PlaywrightCucumberJavaScript/dispatches)

           echo "GitHub API Response Status Code: $status_code"
           
           if [ "$status_code" -ne 204 ]; then
            echo "Failed to trigger automation workflow! Received status code: $status_code"
            exit 1
          fi

          echo "Automation workflow triggered successfully."
