name: Build and Deploy

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Build
        run: |
          echo "Building the project..."
          # Add your actual build commands here
          sleep 5s

      - name: Trigger Automation Tests
        run: |
          curl -X POST -H "Accept: application/vnd.github.everest-preview+json" \
               -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
               --data '{"event_type": "trigger-automation"}' \
               https://github.com/Indra512/PlaywrightCucumberJavaScript/dispatches
